---
- name: Ping all virtual machines and gather OS and kernel information
  hosts: all
  tasks:
    - name: Ping hosts
      ansible.builtin.ping:

    - name: Gather OS and kernel information
      ansible.builtin.shell: |
        cat /etc/os-release
        uname -r
      register: os_info

    - debug:
        msg: "{{ os_info.stdout_lines }}"
